### ISSUE TITLE
<Tabsets> and <nbconvert --embed-images> can't be used together when exporting notebooks to html reports

### ISSUE THREAD

**Issue by chengfeng-liu** [JanPalasek/pretty-jupyter#67] opened 2023-06-26 17:15 UTC
Hello, Pretty Jupyter team,

Thank you for sharing this project and I really love the functionalities.

However, I think I found an issue that:

**If I need to use the `tabsets` functionality, I can't use `--embed-images` in nbconvert when exporting, because using `<--embed-images>` will cause issues to the `tabsets` functionality.**

Can you take a look at this issue? Many thanks!

Regards,
Chengfeng Liu

**Comment by JanPalasek** [comment] 2023-06-27 12:27
Hello. Sure. I'll look into it asap.

**Comment by JanPalasek** [comment] 2023-06-30 19:41
Thank you for reporting it. I managed to reproduce the issue and I'm looking into it.

**Comment by JanPalasek** [comment] 2023-07-03 19:11
I found the problem. The problem is on the side of nbconvert. It cannot handle HTML properly when embed_images is turned on.

The problem is because of the following steps:

1. pretty-jupyter transforms `[//]: # (-.- .tabset)` into `<span class="pj-token" style="display: none">`
2. nbconvert (if embed_images is turned on) in `IPythonRenderer.inline_html` loads first part of the span (due to tokenization) as `<span class="pj-token" style="display: none">`.
3.  If embed_images is turned on, it tries to load it as html using beautiful soup package and then replace the sources with the embedded strings. However when loading it, it "fixes" the html and fills the closing tag for the span => `<span class="pj-token" style="display: none"></span>`.
4. Then the problem snowballs. Now the span is already closed, so it needs to handle ".tabset" text token. So it just appends it after the span etc.

This problem has a simple fix. If the token in `IPythonRenderer.inline_html` does not contain any image tag, the inline_html shouldn't return html parsed for images.

@chengfeng-liu All in all, I know how to fix it in nbconvert package. I'll try to create a merge request to nbconvert asap. Just need to create minimal reproducible example before that explaining why they should want the change.

**Comment by JanPalasek** [comment] 2023-07-03 19:17
Temporary solution:

**Try to install nbconvert < 7.0.0. I tried version 6.5.4 and it works with no issues.**

**Comment by chengfeng-liu** [comment] 2023-07-07 07:23
Great! Thank you so much for looking at it.

I am a heavy user of pretty jupyter and I also found, I think, a minor flaw that the generated html has a huge space of blank at the end. I don't if you call it an issue, but I think the generated html would look better without the blank space at the end.

Thank you again for your time and your package,
Best wishes

**Comment by JanPalasek** [comment] 2023-07-08 16:52
@chengfeng-liu I created issues in nbconvert's repository. I found more issues in the >=7 version of nbconvert, therefore in the new version I limit the required nbconvert's version to <7 in the new release.

I'll be closing this issue since the problem is not in this repository.

**Closed by JanPalasek** 2023-07-08 16:52 UTC
Labels: bug
